baseURL = "https://taitcm.ch/blog/"
title = "TAI TCM Clinic"
theme = "hugo-bearblog"  # 只是个名字，我们会手动补齐文件夹
defaultContentLanguage = "de"

[languages]
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/de"
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
